//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrators
    {
        [DisplayName("Логін")]
        [Required(ErrorMessage = "Обов'язково до заповнення")]
        [MinLength(3,ErrorMessage = "Мінімальна жовжина повинна бути 3")]
        public string login { get; set; }
        [MinLength(3,ErrorMessage = "Мінімальна жовжина повинна бути 3")]
        [Required(ErrorMessage = "Обов'язково до заповнення")]
        [DisplayName("Пароль")]
        public string password { get; set; }
        [MinLength(3,ErrorMessage = "Мінімальна жовжина повинна бути 3")]
        [Required(ErrorMessage = "Обов'язково до заповнення")]
        public string roles { get; set; }
        public Nullable<int> lecturerId { get; set; }    
        [DisplayName("Лектор")]
        public virtual Lecturer Lecturers { get; set; }
    }
}
