//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Administrators
    {
        [DisplayName("Логін")]
        public string login { get; set; }
        [DisplayName("Пароль")]
        public string password { get; set; }
        [DisplayName("Роль")]
        public string roles { get; set; }
    }
}
