//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disciplines()
        {
            this.Group = new HashSet<Group>();
        }
    
        public int id { get; set; }
        [DisplayName("Назва")]
        [MinLength(3,ErrorMessage = "Мінімальна жовжина повинна бути 3")]
        [Required(ErrorMessage = "Обов'язково до заповнення")]
        public string name { get; set; }
        [DisplayName("Кафедра")]
        [MinLength(3,ErrorMessage = "Мінімальна жовжина повинна бути 3")]
        [Required(ErrorMessage = "Обов'язково до заповнення")]
        public string kafedra { get; set; }
        [DisplayName("Курс")]
        [MinLength(3,ErrorMessage = "Мінімальна жовжина повинна бути 3")]
        [Required(ErrorMessage = "Обов'язково до заповнення")]
        public int course { get; set; }
        [DisplayName("Опис")] 
        [MinLength(3,ErrorMessage = "Мінімальна жовжина повинна бути 3")]
        [Required(ErrorMessage ="Обов'язково до заповнення")]
        public string description { get; set; }
        public Nullable<int> lecturerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Group { get; set; }
        public virtual Lecturer Lecturers { get; set; }
    }
}
