//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lecturer()
        {
            this.Administrators = new HashSet<Administrators>();
            this.Disciplines = new HashSet<Disciplines>();
        }
    
        public int Id { get; set; }
        [DisplayName("П.І.Б")] 
        [MinLength(3,ErrorMessage = "Мінімальна жовжина повинна бути 3")]
        [Required(ErrorMessage ="Обов'язково до заповнення")]
        public string fullName { get; set; }
        [DisplayName("Телефон")] 
        [Required(ErrorMessage ="Обов'язково до заповнення")]
        public string phone { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administrators> Administrators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disciplines> Disciplines { get; set; }
    }
}
