//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsTest
    {
        public string id { get; set; }
        public string fio { get; set; }
        public int course { get; set; }
        public string group { get; set; }
        public double AverageMark { get; set; }
        public bool Deleted { get; set; }
        public bool locked { get; set; }
        public string eMail { get; set; }
        public string phoneNumber { get; set; }
    }
}
