//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsInGroups
    {
        public int id { get; set; }
        public int groupID { get; set; }
        public string studentID { get; set; }
        public System.DateTime DateOfRegister { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Students Students { get; set; }
    }
}
