//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.StudentsInGroups = new HashSet<StudentsInGroups>();
        }
        
        public string id { get; set; }
        [DisplayName("Фіо")]
        public string fio { get; set; }
        [DisplayName("Курс")]
        public int course { get; set; }
        [DisplayName("Група")]
        public string group { get; set; }
        [DisplayName("Середній бал")]
        public double AverageMark { get; set; }
        [DisplayName("Пошта")]
        public string eMail { get; set; }
        [DisplayName("Телефон")]
        public string phoneNumber { get; set; }
        [DisplayName("Видалений")]
        public bool Deleted { get; set; }
        [DisplayName("Заблокований")]
        public bool locked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsInGroups> StudentsInGroups { get; set; }
        public virtual Users Users { get; set; }
    }
}
